# Use the official Bun image as the base image
FROM oven/bun:latest

# Set the working directory
WORKDIR /frontend

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Build the application
RUN bun run build